36 send welcome mail to new user
HYF-Connect/hyf-connect pull request #110
Opened 2022-01-08 12:03 UTC by Moamin-AbuEwaida

I used an easy library called nodemailer to send an automatic welcoming email to new registered user into the platform
to have this branch working into your local machine you need to:
- run >> npm install nodemailer OR just run >> npm install
- in your .env file you need to add GEmail=hyfconnect@gmail.com and GPassword=HappyLlamas15
- register with a new email wasn't used before in your local users database :+1:

2022-01-09 14:22 UTC, dirk-jacobs requested changes
I have the impression that this works rather well ewecpt the logo
That's because the logo has a relative path. This works inside the application but not outside the application
<img width="60" src="../../client/assets/assets/logo_pc_full.png"
                                    title="logo" alt="logo">
You will need a refernce that is absolute: https://heroku......

For the rest, great Job !

2022-01-09 14:22 UTC, dirk-jacobs commented on api/utils/welcome-email.js
> +                                <img width="60" src="../../client/assets/assets/logo_pc_full.png"
This will never work if you are not running inside your application
You'll need something like: https://.......

2022-01-09 14:47 UTC, Hajir-pro approved these changes, later dismissed

2022-01-11 16:19 UTC, Moamin-AbuEwaida commented
@rayanejsilva 
showing logo part is done
resolving conflicts is done :+1:

2022-01-11 16:32 UTC, merged