42 mobile header menu
HYF-Connect/hyf-connect pull request #125
Opened 2022-01-11 21:49 UTC by perezrei

This is the burger menu for the mobile version.
I pushed resized images in homepage and the logo in the header

2022-01-11 23:05 UTC, dirk-jacobs requested changes
Overall looks good.
Signout / Sign In should be refined
For this, just check how it's done in the header and avatar

2022-01-11 23:05 UTC, dirk-jacobs commented on client/components/header-component.js
> +          <a class="burger-link" href="/pages/user-profile/user-profile.html">sign out</a>
Sign out should not be visible if not signed in.
There should also a method be attached to clear the token

2022-01-12 11:52 UTC, dirk-jacobs approved these changes
This is a working version

2022-01-12 11:56 UTC, perezrei commented
Good, I'll let everyone know that

2022-01-12 12:03 UTC, Hajir-pro approved these changes

2022-01-12 12:17 UTC, merged