12 create user type table
HYF-Connect/hyf-connect pull request #43
Opened 2021-12-15 13:06 UTC by Moamin-AbuEwaida

in the PR I commented the part at sync.js file where we require user-type.js file
files created:
- user-type.js
- create-user-type.js

*NOTE* when I ran the code this way on my machine, it didn't work. That's why I required user-type file at sync.js file to test then commented the line of code

2021-12-15 14:24 UTC, rayanejsilva requested changes
In the user.js you need to require user-type and change through attribute as a model.

2021-12-16 07:28 UTC, Moamin-AbuEwaida commented
> In the user.js you need to require user-type and change through attribute as a model.

I believe this would work normally when we have both files, type.js and user-type.js as user-type is the join table between the user 's and the type's table :thinking:

2021-12-16 10:10 UTC, Moamin-AbuEwaida commented
@rayanejsilva 
just required user-type into user.js file :+1:

2021-12-16 10:25 UTC, rayanejsilva approved these changes

2021-12-16 10:25 UTC, merged