21 create login page
HYF-Connect/hyf-connect pull request #81
Opened 2021-12-24 09:48 UTC by Moamin-AbuEwaida

I'm pushing the the login page folder with these files:
- login.html
- login.js
- main-section.js
- form-section.js

the page is behaving good in terms of login and connected to the signup page
still the header and footer not added to the development branch to be add to the login page

2021-12-24 13:01 UTC, dirk-jacobs requested changes
Looks good.
Just read my remark about the class-style naming

I didn't checked if everything is working perfectly with the backend, but the basics are there and could be submitted

2021-12-24 13:01 UTC, dirk-jacobs commented on client/styles/login.css
> +.main {
Just to be sure that there is no impact from other style files, I would prefix the style classes with login-  eg login-form_title

2021-12-27 13:00 UTC, Moamin-AbuEwaida commented on client/styles/login.css
> +.main {
noted @dirk-jacobs

2021-12-27 15:35 UTC, Moamin-AbuEwaida commented
just pushed the final commit with the latest edits and updates to the branch files

2021-12-27 21:18 UTC, dirk-jacobs requested changes
In code there is bcryptje in package.json there is bcrypt

2021-12-27 21:27 UTC, Moamin-AbuEwaida commented
> In code there is bcryptje in package.json there is bcrypt


yes, when I install locally bcrypt, i've been getting broken files so I'm using bcryptjs but the rest of the team use bcrypt @dirk-jacobs 
Rayane reviewed the branch from herside- replaced bcryptjs with bcrypt in the business logic folders (login and user) then the server worked normally but now were are receiving a bug for connecting to the database server, the code was working with me when i was running it locally :thinking:

2021-12-28 12:50 UTC, rayanejsilva approved these changes

2021-12-28 12:51 UTC, merged