creating project and adding a new project process is working
HYF-Connect/hyf-connect pull request #85
Opened 2021-12-24 12:30 UTC by Moamin-AbuEwaida

the backend side for creating a project, calling all projects is working perfectly, just remaining calling a project with projetcID

2021-12-26 11:28 UTC, dirk-jacobs requested changes
Next to a number of changes, there is a problem with the autoincrement in case you inserted a project and specified a ProjectID because appearantly the 'internal counter' is not incremented in this case. Solutions found so far:
- start with an empty db
- Retry a number of times because with every try, the internal counter is incremented. After about 5 times, it's starting to work
- Don't specify the ProjectID during creation of the initial records and hope they will be 1,2,3

https://github.com/sequelize/sequelize/issues/5954

2021-12-26 11:28 UTC, dirk-jacobs commented on api/controllers/project.js
> +const project = await projectManager.getProject(projectId);
The function is called getProjectById

2021-12-26 11:28 UTC, dirk-jacobs commented on api/business-logic/project.js
> +getProjectbyId: async(projectId) =>{
Use correct  camel-case:
getProjectById iso getProjectbyId

2021-12-26 11:28 UTC, dirk-jacobs commented on api/business-logic/project.js
> +const project = await ProjectStore.find(projectId);
Use findByPk in this case

2021-12-26 11:28 UTC, dirk-jacobs commented on api/access.log
>  ::ffff:127.0.0.1 - - [22/Dec/2021:18:59:42 +0000] "GET /pages/homepage/banner-section.js HTTP/1.1" 200 548 "http://127.0.0.1:3000/pages/homepage/homepage.js" "Mozilla/5.0 (X11; Linux x86_64) AppleWeb
PLease delete this file and add it to .gitignore

2021-12-26 11:28 UTC, dirk-jacobs commented on api/routes/project.js
> +projectRoutes.post("/addProject", projectController.post);
The default for a post is an insert
For me, "addProject" is not needed

This is ok
projectRoutes.post("/", projectController.post);

2021-12-27 11:16 UTC, Moamin-AbuEwaida commented
Thanks @dirk-jacobs for the followup comments
I edited the branch files accordingly but I still have the same thing for calling a certain project by projectId at postman and I receive the array of all the project :thinking: 
another weird response I have is when I'm checking the DB using pgAdmin tool, I still can't see any project added to the table even the 1st 3 project added during the testing of scripts>>create-project.js

2021-12-28 16:58 UTC, dirk-jacobs requested changes
There seems to be a merge confoct in index.js which needs to be fixed first

2021-12-28 16:58 UTC, dirk-jacobs commented on api/routes/index.js
> +<<<<<<< HEAD
There seems to be a merge conflict

2021-12-28 18:20 UTC, Moamin-AbuEwaida commented on api/routes/index.js
> +<<<<<<< HEAD
I'll check it out

2022-01-02 14:50 UTC, rayanejsilva approved these changes
LGTM!

2022-01-02 14:50 UTC, rayanejsilva commented on api/business-logic/project.js
> +    try {
You can remove try/catch. You already moved this part to controllers.

2022-01-02 14:51 UTC, merged