removed header.html
HYF-Connect/hyf-connect pull request #86
Opened 2021-12-24 13:38 UTC by firity

2021-12-25 10:52 UTC, dirk-jacobs requested changes
We are making progress: 'Close but no cigar'
Please update the links and as a bonus: do you think it is possible to make the updates you did in the about-us.html page (google fonts + link to styles.css)  also in the members.html, projects.html and contact-us.html ?

2021-12-25 10:52 UTC, dirk-jacobs commented on client/components/header-component.js
> +            <a href="https:" class="logo"><img src="/public/assets/logo_pc_full.png" alt="logo" width="90" height="70"/></a>
Clicking on the logo should bring us back to the homepage..
Replace the link of the logo (currently https: ??? with /pages/homepage/homepage.html or just /

2021-12-25 10:52 UTC, dirk-jacobs commented on client/components/header-component.js
> +            <a class="sign-in-btn" href="/pages/sign-in.html">Sign-in</a>
The link to the signup page is incorrect
/pages/sign-in/sign-in.html

2021-12-25 18:46 UTC, dirk-jacobs approved these changes, later dismissed
Looks ok to me

2021-12-27 10:38 UTC, rayanejsilva reviewed
@firity I adjusted link paths in the nav-bar.

2021-12-27 10:40 UTC, rayanejsilva approved these changes

2021-12-27 11:40 UTC, Moamin-AbuEwaida approved these changes
LGTM
we'll have a conflict with the sign in naming as i changed it to login in my branch to skip the confusion 
Thanks @firity

2021-12-27 11:41 UTC, merged