19 create members page
HYF-Connect/hyf-connect pull request #94
Opened 2021-12-29 05:17 UTC by Moamin-AbuEwaida

members page has member ticket component, the component data now is static and should be changing dynamically after fetching data from the backend

2021-12-29 07:34 UTC, Hajir-pro submitted a review, later dismissed

2021-12-29 22:00 UTC, dirk-jacobs requested changes
There us still some work to do.
But even as a first version, I would like to see some changes.
Please check the benefits or testimonials in the homepage

2021-12-29 22:00 UTC, dirk-jacobs commented on client/pages/members/memebers-ticket-section.js
> +export const membersTicketSection = {
This is not really a Section but a component.
I would rename this to MemberComponent and the file to member-component.js

2021-12-29 22:00 UTC, dirk-jacobs commented on client/pages/members/members.js
> +<members-ticket-section></members-ticket-section>
I would introduce a MemberSection which 'loops' over the different MemberComponent
As an example, check BenefitsSection in the homepage

2022-01-03 16:56 UTC, Moamin-AbuEwaida commented
i edited the MembersComponents / MembersSection according to the  BenefitsSection in the homepage way
I'll start with backend connection so  MemberComponent loops through the users to call back the data from DB @dirk-jacobs

2022-01-04 14:55 UTC, Moamin-AbuEwaida commented
I managed to fetch the user's data from the database as well as the users skill -added the functions to business logic, controller and routes user.js- also succeeded to present the needed data into the frontend part 
for not receiving errors in the console i commented the lines for the skills selection part as still work needed to be :thinking:

2022-01-10 14:17 UTC, merged